version: '3.8'

services:
  postgres:
    container_name: enqueti-postgresql
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=enqueti
      - POSTGRES_PASSWORD=enqueti
      - POSTGRES_DB=enqueti_db
    networks:
      - backend_network
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'polls_redis_data:/bitnami/redis/data'

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
  polls_redis_data: